### ISSUE TITLE
[Bug] Shift clicking into full inventory deletes item in shulker box

### ISSUE THREAD

**Issue by Folas1337** [Phoenix616/OpenShulkerBoxes#1]
#### Used Version
OpenShulkerBoxes version 1.0.1-SNAPSHOT (build 26)
 
 
#### Config
<details>
          <summary>Config</summary>

 ```yaml
openable-items:
- "*_shulker_box"
- "shulker_box"
open:
  in-inventory: right
#  in-creative: right # Creative is broken ;_;
  from-hotbar:
    action:
    - right_click_air
    sneaking: false
 ```
 
</details>
 
#### Environment description
This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
 
 
#### Full Log
<details>
          <summary>Log</summary>

```
[Your log here]
```

</details>

#### What other programs/plugins are you running?
I'm using plenty of plugins, none of them should be causing this issue. I will later verify that it's happening without any other plugins, for now I wanted to report it with all the information I have.

#### What is happening?
Suppose you have a full inventory with a shulker box. Open the shulker box with the plugin by right clicking and then shift click an item into your inventory. The item that should have been transferred will be deleted entirely.

#### What did you expect to happen?
The item doesn't move and just stays where it is.

#### Additional context
Here is a video of it happening: https://youtu.be/UEP1TDyUuO0
